[project]
authors = [{ name = "reggie-db", email = "reggie.pierce@databricks.com" }]
dependencies = [
    "dash",
    "dynaconf",
    "giturlparse",
    "psutil",
    "pyyaml",
    "requirements-parser",
    "waitress",
]
name = "reggie-app-runner"
requires-python = ">= 3.11"
version = "0.1.0"

[project.scripts]
reggie-app-runner = "reggie_app_runner.cli:main"

[build-system]
requires = ["uv_build>=0.9.6"]
build-backend = "uv_build"

[dependency-groups]
dev = ["lfp-build @ git+https://github.com/regbo/lfp-build-py.git", "pytest"]

[tool.pixi.activation]
env = { GOBIN = "$PIXI_PROJECT_ROOT/.pixi/go/bin", PATH = "$GOBIN:$PATH" }

[tool.pixi.workspace]
channels = ["https://prefix.dev/regbo", "conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
reggie_app_runner = { path = ".", editable = true }

[tool.pixi.dependencies]
caddy = ">=2.10.0,<3"
portrc = ">=0.1.26,<0.2"

[tool.pixi.tasks]
uvr = "uv run"
uvm = "uv run -m"

[tool.pytest.ini_options]
pythonpath = ["src"]
